# Generated by Django 4.1.7 on 2023-11-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
